version: "3"
services:
  app:
    image: larvel-www
    container_name: laravel-www
    build:
      context : .
      dockerfile: docker/Dockerfile
    ports:
      - 8888:80
  mysql:
    container_name: laravel-mysql
    image: mysql:5.7
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    ports:
      - 13306:3306
  redis:
    container_name: laravel-redis
    image: redis:4-alpine
    ports:
      - 16379:6379
    volumes:
      - redis:/data
volumes:
  mysql:
    driver: "local"
  redis:
    driver: "local"
